//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.RouteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RouteService.IRouteService")]
    public interface IRouteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteService/InitCache", ReplyAction="http://tempuri.org/IRouteService/InitCacheResponse")]
        void InitCache();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteService/InitCity", ReplyAction="http://tempuri.org/IRouteService/InitCityResponse")]
        void InitCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteService/SearchRoute", ReplyAction="http://tempuri.org/IRouteService/SearchRouteResponse")]
        string SearchRoute(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteService/GetCities", ReplyAction="http://tempuri.org/IRouteService/GetCitiesResponse")]
        string[] GetCities();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRouteServiceChannel : Client.RouteService.IRouteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RouteServiceClient : System.ServiceModel.ClientBase<Client.RouteService.IRouteService>, Client.RouteService.IRouteService {
        
        public RouteServiceClient() {
        }
        
        public RouteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RouteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InitCache() {
            base.Channel.InitCache();
        }
        
        public void InitCity(string city) {
            base.Channel.InitCity(city);
        }
        
        public string SearchRoute(string origin, string destination) {
            return base.Channel.SearchRoute(origin, destination);
        }
        
        public string[] GetCities() {
            return base.Channel.GetCities();
        }
    }
}
